export let HEALTH_REAL_TIME = {
  steps: 0,
  distance: 0,
  appleExcerciseTime: 0,
  calories: 0,
  activity: 0,
  height: 0,
  weight: 0,
  heart_rate: 0,
  heart_rate_resting: 0,
  heart_rate_variability: 0,
  resp_rate: 0,
  vo2max: 0,
  temperature: 0,
  fat_percentage: 0,
  waist_circunference: 0,
  blood_glucose: 0,
  insulin: 0,
  blood_pressure: 0,
  blood_pressure_systolic: 0,
	blood_pressure_diastolic: 0,
  gender: '',
  date_of_birth: '',
  mindfulness: '',
  nutrition: '',
  sleep: {}
};

export let HEALTH_DAILY = {
  steps: 0,
  distance: 0,
  appleExcerciseTime: 0,
  calories: 0,
  activity: 0,
  height: 0,
  weight: 0,
  heart_rate: 0,
  heart_rate_resting: 0,
  heart_rate_variability: 0,
  resp_rate: 0,
  vo2max: 0,
  temperature: 0,
  fat_percentage: 0,
  waist_circunference: 0,
  blood_glucose: 0,
  insulin: 0,
  blood_pressure: 0,
  blood_pressure_systolic: 0,
	blood_pressure_diastolic: 0,
  gender: '',
  date_of_birth: '',
  mindfulness: '',
  nutrition: '',
  sleep: {}
};

export let HEALTH_WEEKLY = {
  steps: 0,
  distance: 0,
  appleExcerciseTime: 0,
  calories: 0,
  activity: 0,
  height: 0,
  weight: 0,
  heart_rate: 0,
  heart_rate_resting: 0,
  heart_rate_variability: 0,
  resp_rate: 0,
  vo2max: 0,
  temperature: 0,
  fat_percentage: 0,
  waist_circunference: 0,
  blood_glucose: 0,
  insulin: 0,
  blood_pressure: 0,
  blood_pressure_systolic: 0,
	blood_pressure_diastolic: 0,
  gender: '',
  date_of_birth: '',
  mindfulness: '',
  nutrition: '',
  sleep: {}
};

export let HEALTH_MONTHLY = {
  steps: 0,
  distance: 0,
  appleExcerciseTime: 0,
  calories: 0,
  activity: 0,
  height: 0,
  weight: 0,
  heart_rate: 0,
  heart_rate_resting: 0,
  heart_rate_variability: 0,
  resp_rate: 0,
  vo2max: 0,
  temperature: 0,
  fat_percentage: 0,
  waist_circunference: 0,
  blood_glucose: 0,
  insulin: 0,
  blood_pressure: 0,
  blood_pressure_systolic: 0,
	blood_pressure_diastolic: 0,
  gender: '',
  date_of_birth: '',
  mindfulness: '',
  nutrition: '',
  sleep: {}
};

export let HEALTH_YEARLY = {
  steps: 0,
  distance: 0,
  appleExcerciseTime: 0,
  calories: 0,
  activity: 0,
  height: 0,
  weight: 0,
  heart_rate: 0,
  heart_rate_resting: 0,
  heart_rate_variability: 0,
  resp_rate: 0,
  vo2max: 0,
  temperature: 0,
  fat_percentage: 0,
  waist_circunference: 0,
  blood_glucose: 0,
  insulin: 0,
  blood_pressure: 0,
  blood_pressure_systolic: 0,
	blood_pressure_diastolic: 0,
  gender: '',
  date_of_birth: '',
  mindfulness: '',
  nutrition: '',
  sleep: {}
};